# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for bacon configurations
Name: jolla-configuration-bacon
Requires:
- pattern:jolla-hw-adaptation-bacon
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland

- sailfish-content-graphics-z@ICON_RES@

# are these still needed?
- jolla-ambient-z@ICON_RES@
- ambient-icons-closed-z@ICON_RES@

# For devices with cellular modem. Those without one, please comment out:
- pattern:jolla-sailfish-cellular-apps

# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

# why is this not installed by default? 
- jolla-settings-accounts-extensions-jolla
- jolla-settings-system-sideloading
- store-client

# Introduced starting Sailfish OS 2.0.4.x:
# # 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all
- jolla-settings-sailfishos

# these might come in handy and should be installed from the store
# still a phone without these is rather useless
#- jolla-email
#- jolla-calendar
#- jolla-calculator
#- jolla-mediaplayer

# these might come in handy as well
- jolla-settings-accounts-extensions-jabber
- jolla-settings-accounts-extensions-email
# not usefull yet
#- jolla-settings-accounts-extensions-sip

Summary: Jolla Configuration bacon

