# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for bacon configurations
Name: jolla-configuration-bacon
Requires:
- patterns-sailfish-device-configuration-bacon

Summary: Jolla Configuration bacon

